version: 2

project_name: telekom-gfmodem2-exporter

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/telekom-gfmodem2-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - "6"
      - "7"
    gomips:
      - hardfloat
      - softfloat

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
